/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BancodeDados.Conexao;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author soare_000
 */
public final class GetProtocolo extends javax.swing.JFrame {

    private int idProtocolo = 0;

    /**
     * Creates new form NewJFrame1
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public GetProtocolo() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocation(350, 80);
        listarAssunto(0);
        jTextipo.setBackground(Color.white);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAssunto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GetData = new javax.swing.JTextField();
        GetAssunto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        GetDescricao = new javax.swing.JTextPane();
        Gethora = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        GetProtocolo = new javax.swing.JFormattedTextField();
        jTextipo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboSelecioneMes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Judith: Ver Protocolos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ver Protocolos");
        jLabel1.setToolTipText("");

        jTableAssunto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "Assunto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAssunto.setColumnSelectionAllowed(true);
        jTableAssunto.setGridColor(new java.awt.Color(153, 102, 0));
        jTableAssunto.setName(""); // NOI18N
        jTableAssunto.getTableHeader().setReorderingAllowed(false);
        jTableAssunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAssuntoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAssunto);
        jTableAssunto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTableAssunto.getColumnModel().getColumnCount() > 0) {
            jTableAssunto.getColumnModel().getColumn(0).setMinWidth(0);
            jTableAssunto.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableAssunto.getColumnModel().getColumn(0).setMaxWidth(0);
            jTableAssunto.getColumnModel().getColumn(1).setMinWidth(0);
            jTableAssunto.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTableAssunto.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("Clique no assunto para ver os detalhes");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(153, 102, 0));
        jLabel3.setText("Protocolo: ");

        jLabel4.setForeground(new java.awt.Color(153, 102, 0));
        jLabel4.setText("Data e Hora : ");

        jLabel5.setForeground(new java.awt.Color(153, 102, 0));
        jLabel5.setText("Assunto:");

        jLabel6.setForeground(new java.awt.Color(153, 102, 0));
        jLabel6.setText("Descrição: ");

        GetData.setEditable(false);
        GetData.setBackground(new java.awt.Color(255, 255, 255));
        GetData.setBorder(null);
        GetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDataActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(GetDescricao);

        Gethora.setEditable(false);
        Gethora.setBackground(new java.awt.Color(255, 255, 255));
        Gethora.setBorder(null);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(153, 102, 0));
        jButton3.setText("Salvar alterações");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        try {
            GetProtocolo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        GetProtocolo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextipo.setEditable(false);
        jTextipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextipo.setForeground(new java.awt.Color(153, 102, 0));
        jTextipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextipo.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(GetData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gethora, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GetAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(GetProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextipo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextipo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gethora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(42, 42, 42))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(153, 102, 0));
        jButton1.setText("Novo Protocolo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(153, 102, 0));
        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(153, 102, 0));
        jButton4.setText("Remover Protocolo Selecionado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboSelecioneMes.setForeground(new java.awt.Color(153, 102, 0));
        jComboSelecioneMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", " " }));
        jComboSelecioneMes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 1, true));
        jComboSelecioneMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboSelecioneMesMouseClicked(evt);
            }
        });
        jComboSelecioneMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSelecioneMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboSelecioneMes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(72, 72, 72)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboSelecioneMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetDataActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SetProtocolo acessa = null;
        try {
            acessa = new SetProtocolo();
        } catch (SQLException ex) {
            Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
        }
        acessa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked
//Função que exibirá os detalhes do protocolo ao clicar nele.
    private void jTableAssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAssuntoMouseClicked
//JOptionPane.showMessageDialog(rootPane,jTableAssunto.getSelectedRow()+jTableAssunto.getValueAt(jTableAssunto.getSelectedRow(), 1));
//System.out.println("o tipo selecionado é "+ jTableAssunto.getValueAt(jTableAssunto.getSelectedRow(), 1));        
        idProtocolo = Integer.parseInt((String) jTableAssunto.getValueAt(jTableAssunto.getSelectedRow(), 0));
        try {
            try {
                VerDetalhesProtocolo(idProtocolo);
            } catch (ParseException ex) {
                Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableAssuntoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if ((GetAssunto.getText().equals("")) | (GetDescricao.getText().equals("")) | (GetProtocolo.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");//adiciona um label ao lado do JtextField  
        } else {
            Conexao atualiza = new Conexao();
            int retorno = 0;
            try {
                atualiza.atualizaProtocolo(idProtocolo, GetProtocolo.getText(), GetData.getText(), Gethora.getText(), GetAssunto.getText(), GetDescricao.getText());
                if (retorno == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Protocolo alterado com sucesso!");
                    try {
                        listarAssunto(0);
                    } catch (SQLException ex) {
                        Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pesquisar a = new Pesquisar();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Conexao a = new Conexao();
        int descisao = 20;
        descisao = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover este protocolo?", null, WIDTH, WIDTH, null);
        if (descisao == 0) {

            try {
                a.removeProtocolo(idProtocolo);
                GetProtocolo.setText(null);
                GetData.setText(null);
                Gethora.setText(null);
                GetProtocolo.setText(null);
                GetDescricao.setText(null);
                GetAssunto.setText(null);
                listarAssunto(0);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboSelecioneMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSelecioneMesActionPerformed
System.out.println("você selecionou: "+jComboSelecioneMes.getSelectedItem());        // TODO add your handling code here:
try {
    if(jComboSelecioneMes.getSelectedItem()=="Selecione o mês")  listarAssunto(0);
else
if(jComboSelecioneMes.getSelectedItem()=="Janeiro")
    listarAssunto(1);
else
if(jComboSelecioneMes.getSelectedItem()=="Fevereiro")listarAssunto(2);
else
if(jComboSelecioneMes.getSelectedItem()=="Março")listarAssunto(3);
else
if(jComboSelecioneMes.getSelectedItem()=="Abril")listarAssunto(4);
else
if(jComboSelecioneMes.getSelectedItem()=="Maio")listarAssunto(5);
else
if(jComboSelecioneMes.getSelectedItem()=="Junho")listarAssunto(6);
else
if(jComboSelecioneMes.getSelectedItem()=="Julho")listarAssunto(7);
else
if(jComboSelecioneMes.getSelectedItem()=="Agosto")listarAssunto(8);
else
if(jComboSelecioneMes.getSelectedItem()=="Setembro")listarAssunto(9);
else
if(jComboSelecioneMes.getSelectedItem()=="Outubro")listarAssunto(10);
else
if(jComboSelecioneMes.getSelectedItem()=="Novembro")listarAssunto(11);
else
if(jComboSelecioneMes.getSelectedItem()=="Dezembro")listarAssunto(12);
} catch (ClassNotFoundException ex) {
    Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
} catch (SQLException ex) {
    Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jComboSelecioneMesActionPerformed

    private void jComboSelecioneMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboSelecioneMesMouseClicked

    }//GEN-LAST:event_jComboSelecioneMesMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
new Conexao().encerraXampp();//encerrar o servidor
    }//GEN-LAST:event_formWindowClosing
    public void listarAssunto(int mes) throws ClassNotFoundException, SQLException {
    //que listara os protocolos do banco de dados
        //*******************limpa consultas anteriores
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) jTableAssunto.getModel();
        tabela.setNumRows(0);
        //********************************************
        ArrayList<Protocolo> listaProtocolo;
        Conexao consultasql = new Conexao();//criando um novo objeto de conexao com o BD
        listaProtocolo = consultasql.selectProtocolos(null,mes);//se o mes for igual a zero a busca retornara todos os meses
        for (int i = 0; i < listaProtocolo.size(); i++) {//laço para preencher a tabela de assunto
            DefaultTableModel valor = (DefaultTableModel) jTableAssunto.getModel();
            String id = Integer.toString(listaProtocolo.get(i).getID());
            String tipoprotocolo = Integer.toString(listaProtocolo.get(i).getTipoProtocolo());
            valor.addRow(new String[]{id, tipoprotocolo, listaProtocolo.get(i).getAssunto()});
        }
    }

    public void VerDetalhesProtocolo(int id) throws ClassNotFoundException, SQLException, ParseException {
        //que listara os protocolos do banco de dados
        ArrayList<Protocolo> listaProtocolo;
        Conexao consultasql = new Conexao();//criando um novo objeto de conexao com o BD
        listaProtocolo = consultasql.selectProtocoloID(id);//chamada a função que exibira os detalhes do protocolo
//----------------------------------------------    
//o codigo abaixo altera a mascara do campo getprotocolo para o formato de protocolo usado pela anatel
        if (listaProtocolo.get(0).getTipoProtocolo() == 1) {
            GetProtocolo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.####")));
        } else if (listaProtocolo.get(0).getTipoProtocolo() == 0) {
            GetProtocolo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##.###.###-##")));
        }
        //----------------------------------------------
        if (listaProtocolo.get(0).getTipoProtocolo() == 0) {
            jTextipo.setText("Protocolo Oi");
        }
        if (listaProtocolo.get(0).getTipoProtocolo() == 1) {
            jTextipo.setText("Protocolo Anatel");
        }
        jTextipo.setBackground(Color.white);//exibe o tipo de protocolo -  oi ou Anatel
        GetProtocolo.setText(listaProtocolo.get(0).getProtocolo());
        GetData.setText(listaProtocolo.get(0).getData());
        Gethora.setText(listaProtocolo.get(0).getHora());
        GetAssunto.setText(listaProtocolo.get(0).getAssunto());
        GetDescricao.setText(listaProtocolo.get(0).getDescricao());
    //System.out.println("Tipo de protocolo: "+listaProtocolo.get(0).getTipoProtocolo());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GetProtocolo().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(GetProtocolo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GetAssunto;
    private javax.swing.JTextField GetData;
    private javax.swing.JTextPane GetDescricao;
    private javax.swing.JFormattedTextField GetProtocolo;
    private javax.swing.JTextField Gethora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboSelecioneMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAssunto;
    private javax.swing.JTextField jTextipo;
    // End of variables declaration//GEN-END:variables

   

}
